### ISSUE TITLE
ESTE ERROR ES MUY GRAVE POR FAVOR AIUDA

### ISSUE THREAD

**Issue by jaimixhu** [mjaque/FakeKnight#2]
el otro dia decidi iniciar este grandioso juego para poder admirar sus hermosos paisajes para nada copiados de soul knigth, pero de repente una pared salvaje aparecio y se comio a mi familia, quiero un reembolso gracias

**Comment by mjaque** [comment]
Te hemos enviado el reembolso y una expontex para que limipies cualquier resto de sangre y órganos que pudiera quedar.
Ahora puede buscar una nueva familia para seguir jugando.
Gracias por tu comentario :)
