### ISSUE TITLE
una pizza 4 quesos plox

### ISSUE THREAD

**Issue by jaimixhu** [mjaque/FakeKnight#3]
La pizza es un pan plano horneado elaborado con harina de trigo, sal, agua y levadura, y cubierto con salsa de tomate, queso y otros ingredientes como salami, champiñones, cebolla, jamón o aceitunas. Original de la cocina napolitana (Italia), se ha hecho muy popular en todo el mundo y presenta muy diversas variantes. Sin embargo, la pizza napolitana ha sido la única para la que se ha reconocido una denominación de origen propia de la Unión Europea, denominada Especialidad Tradicional Garantizada1​2​ (o sus siglas en italiano, STG, Specialità Tradizionale Garantita). Este reconocimiento se obtuvo el 4 de febrero de 2010 a propuesta de la Associazione Verace Pizza Napoletana.3​

Es un plato de elaboración artesanal en la mayoría de los casos, aunque la industria alimentaria ha ido presentando, desde los años 1950, versiones como un alimento confort en los supermercados. En la actualidad, diversas empresas la distribuyen a domicilio.

**Comment by mjaque** [comment]
Prefiero la tortilla de patatas
